main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_page.urls')),
    path('', include('films.urls')),
    path('', include('tags.urls')),
    path('', include('parser_app.urls')),
    path('', include('users.urls')),
    path('recipes_list/', include('recipes.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                    document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(),name='logout'),
    path('user_list/', views.UserListView.as_view(),name='user_list'),
]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.CharField(max_length=50)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

    def __str__(self):
        return f"{self.name} - {self.quantity}"

templates/components/footer.html
  <footer>
        <p>&copy; 2025 Интернет Кинотеатр | Все права защищены</p>
        <ul>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">Политика конфиденциальности</a></li>
        </ul>
    </footer>

templates/components/header.html
<header>
    <nav class="menu">
        <ul>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'all_product' %}">Хэштеги</a></li>
            <li><a href="{% url 'films_list' %}">Фильмы</a></li>
            <li><a href="{% url 'kinov_list' %}">Другие фильмы</a></li>
            <li><a href="{% url 'parser_form' %}">Парсинг</a></li>
            <li><a href="{% url 'users:register' %}">Регистрация</a></li>
            <li><a href="{% url 'users:login' %}">Войти</a></li>

            <!-- Добавленная ссылка на список рецептов -->
            <li><a href="{% url 'recipe_list' %}">Рецепты</a></li>

            <!-- Форма поиска -->
            <li class="search">
                <form action="{% url 'search' %}" method="GET">
                    <input type="text" name="q" placeholder="Поиск...">
                    <button type="submit">Поиск</button>
                </form>
            </li>
        </ul>
    </nav>
</header>